name: Schedule Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print current UTC time
        run: |
          echo "Current UTC time: $(date -u)"
          echo "This should run around 03:00 your local time"
